apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: logging

data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://logs.manjilgautam.com.np/loki/api/v1/push
        basic_auth:
          username: lokiadmin
          password: "N0de@xP0&t#r"
        batchwait: 1s
        batchsize: 1048576

    scrape_configs:

      - job_name: kubernetes-pods

        kubernetes_sd_configs:
          - role: pod

        pipeline_stages:
          - docker: {}

        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

          - source_labels: [__meta_kubernetes_container_name]
            target_label: container

          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node

          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: job