apiVersion: traefik.io/v1alpha1
kind: Middleware

metadata:
  name: crowdsec-bouncer
  namespace: kube-system

spec:

  plugin:

    crowdsec-bouncer:

      enabled: true

      crowdsecMode: live

      crowdsecAppsecEnabled: false

      crowdsecLapiScheme: http

      crowdsecLapiHost: crowdsec-lapi.crowdsec.svc.cluster.local:8080

      crowdsecLapiKey: REPLACE_ME