apiVersion: v1
kind: ConfigMap

metadata:
  name: crowdsec-config
  namespace: crowdsec

data:

  acquis.yaml: |

    filenames:
      - /var/log/containers/*traefik*.log

    labels:
      type: traefik

  profiles.yaml: |

    name: default_ip_remediation

    filters:
      - Alert.Remediation == true

    decisions:
      - type: ban
        duration: 4h

  local_api_credentials.yaml: |

    url: http://crowdsec-lapi:8080