networks:
  traefik-net:
    name: traefik-net
    driver: bridge
services:

  # =========================
  # TRAEFIK (EDGE)
  # =========================
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped

    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-net

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=admin@django-auth.manjilgautam.com.np
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json

      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.filepath=/var/log/traefik/access.log

      - --log.level=INFO

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik-logs:/var/log/traefik

    networks:
      - traefik-net
  
        

# =========================
  django-web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: django-web
    restart: unless-stopped

    environment:
      DJANGO_DEBUG: "0"
      DJANGO_ALLOWED_HOSTS: django-auth.manjilgautam.com.np

      USE_X_FORWARDED_HOST: "1"
      SECURE_PROXY_SSL_HEADER: "HTTP_X_FORWARDED_PROTO,https"

    volumes:
      - .:/app

    networks:
      - traefik-net

  # =========================
  # FAIL2BAN
  # =========================
  fail2ban:
    build:
      context: .
      dockerfile: fail2ban/Dockerfile

    container_name: fail2ban
    restart: unless-stopped

    network_mode: host

    privileged: true

    cap_add:
      - NET_ADMIN
      - NET_RAW

    volumes:
      - ./traefik-logs:/var/log/traefik:ro
      - ./waf-logs:/var/log/modsecurity:ro
      - ./nginx-logs:/var/log/nginx:ro
      - ./fail2ban/jail.d:/etc/fail2ban/jail.d:ro
      - ./fail2ban/filter.d:/etc/fail2ban/filter.d:ro

    depends_on:
      - traefik

