deployment:
  podAnnotations:
    prometheus.io/port: "8082"
    prometheus.io/scrape: "true"

global:
  systemDefaultRegistry: ""

image:
  repository: rancher/mirrored-library-traefik
  tag: 3.6.13

priorityClassName: system-cluster-critical

providers:
  kubernetesIngress:
    publishedService:
      enabled: true

service:
  ipFamilyPolicy: PreferDualStack

logs:
  general:
    level: INFO
  access:
    enabled: true
    format: json

tolerations:
- key: CriticalAddonsOnly
  operator: Exists
- effect: NoSchedule
  key: node-role.kubernetes.io/control-plane
  operator: Exists
