apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - secrets/django-secret.yaml

  - postgres/service.yaml
  - postgres/statefulset.yaml

  - django/service.yaml
  - django/deployment.yaml

  - ingress/ingress.yaml