apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - secrets/django-secret.yaml

  - postgres/service.yaml
  - postgres/statefulset.yaml

  - pgbouncer/service.yaml
  - pgbouncer/deployment.yaml
  - pgbouncer/configmap.yaml

  - django/service.yaml
  - django/deployment.yaml
  - django/hpa.yaml
  - django/pdb.yaml

  - ingress/middleware-ratelimit.yaml
  - ingress/ingress.yaml

  #- fail2ban/configmap.yaml
  #- fail2ban/deployment.yaml

  - cert-manager/clusterissuer.yaml