---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: django-auth
type: Opaque
stringData:
  # IMPORTANT: Replace these with your actual secrets
  DJANGO_SECRET_KEY: "django-insecure-t3&vce_k$0_83z&mwqm%hujf@obywi-wngy%ufzb@xy_s6ab%u"
  POSTGRES_PASSWORD: "postgres-password-change-me"
  DB_PASSWORD: "postgres-password-change-me"
