---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: django-auth
  labels:
    app: traefik
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: web
    protocol: TCP
    name: web
  - port: 443
    targetPort: websecure
    protocol: TCP
    name: websecure
  - port: 8080
    targetPort: dashboard
    protocol: TCP
    name: dashboard
  selector:
    app: traefik
