apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: django-auth
type: Opaque

stringData:
  SECRET_KEY: "MA?567qKaz_MEVS>ep/%5ca<=_aaoaL$Cr)Z<ycg5tSY01+I,r^Y1YGw%%<!*vYypWQKlT6KRm>TgJN0w/BaV9"

  DEBUG: "False"

  ALLOWED_HOSTS: "django-auth.manjilgautam.com.np"

  POSTGRES_DB: "djangoauth"
  POSTGRES_USER: "django"
  POSTGRES_PASSWORD: "Khat42$pwe$#44"

DATABASE_URL: postgresql://django:Khat42%24pwe%24%2344@pgbouncer:6432/djangoauth