apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: django-auth
type: Opaque

stringData:
  SECRET_KEY: "replace-with-random-secret"

  DEBUG: "False"

  ALLOWED_HOSTS: "django-auth.manjilgautam.com.np"

  POSTGRES_DB: "djangoauth"
  POSTGRES_USER: "django"
  POSTGRES_PASSWORD: "StrongPassword123"

  DATABASE_URL: "postgresql://django:StrongPassword123@postgres:5432/djangoauth"