---
apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_DEBUG: "1"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
  USE_X_FORWARDED_HOST: "0"
  SECURE_PROXY_SSL_HEADER: ""
  POSTGRES_HOST: "postgres.django-auth-dev.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "django_dev"
  POSTGRES_USER: "django_dev"
