---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: django-auth-staging

bases:
  - ../../

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: django-app
    count: 2
  - name: postgres
    count: 1
  - name: traefik
    count: 1
  - name: waf
    count: 1

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: HorizontalPodAutoscaler
    metadata:
      name: django-app-hpa
    spec:
      minReplicas: 2
      maxReplicas: 5

  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: django-app
    spec:
      template:
        spec:
          containers:
          - name: django-app
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1Gi"
                cpu: "500m"

resources:
  - configmap-staging.yaml
